"""
Topology classes for HPC Interconnects
Supports: Dragonfly, Folded-Clos, Jellyfish

Extended with intra-server/intra-node topology support:
- Server: Physical machine connected to main topology switch
- Node: Subdivision within server, each with its own NVSwitch/NIC
- NPU: Processing units within each node

The topology switches themselves serve as the ToR:
- Dragonfly: All switches are ToRs
- Jellyfish: All switches are ToRs  
- FoldedClos: Edge switches are ToRs

Intra-node topology types:
- 'switch': NPUs connect to NVSwitch(es), NVSwitch connects to main switch (ToR)
- 'ring': NPUs have switches in a ring, NIC connects to main switch (ToR)
- 'fully_connected': NPUs have fully connected switches, NIC connects to main switch (ToR)
"""

import json, sys
import time, pprint
import random
import networkx as nx
from itertools import permutations, product


class IntraNodeTopologyMixin:
    """
    Mixin class to add intra-server/intra-node topology support.
    
    Hierarchy:
    - Server: Physical machine (generated by topology as a "concentration" unit)
    - Node: Subdivision within server (nodes_per_server)
    - NPU: Processing units within node (npus_per_node)
    
    The main topology switches serve directly as ToRs (no separate ToR level).
    
    Structure for 'switch' topology:
        NPUs <-> NVSwitch(es) <-> main_switch
        
    Structure for 'ring'/'fully_connected' topology:
        NPUs <-> NPU-switches <-> NIC <-> main_switch
    """
    
    def init_intra_node_config(self, nodes_per_server=1, npus_per_node=1, 
                                intra_node_topology=None, num_nvswitches=1, 
                                intra_node_bw=None, inter_node_bw=None,
                                intra_node_latency=None, inter_node_latency=None):
        """Initialize intra-server/intra-node configuration parameters."""
        self.nodes_per_server = nodes_per_server
        self.npus_per_node = npus_per_node
        self.intra_node_topology = intra_node_topology  # 'switch', 'ring', 'fully_connected', or None
        self.num_nvswitches = num_nvswitches  # Only used for 'switch' topology
        self.intra_node_bw = intra_node_bw  # Bandwidth within node (NPU to NVSwitch)
        self.inter_node_bw = inter_node_bw  # Bandwidth to ToR
        self.intra_node_latency = intra_node_latency if intra_node_latency is not None else 0.0
        self.inter_node_latency = inter_node_latency if inter_node_latency is not None else 0.0
        
        # Tracking for topology elements
        self.tor_switches = []  # List of main switches serving as ToRs
        self.nvswitch_ids = []  # List of NVSwitch names (for 'switch' topology)
        self.npu_switches = []  # List of NPU switch names (for ring/fully_connected)
        self.nic_switches = []  # List of NIC switch names (for ring/fully_connected)
        
        # Track hierarchy
        self.server_nodes = {}  # Maps server_id -> list of node_ids
        self.node_npus = {}  # Maps node_id -> list of NPU names
        self.npu_to_intra_switches = {}  # Maps NPU -> list of intra-node switch names
        self.server_to_tor = {}  # Maps server_id -> main switch name (which IS the ToR)
        
    def build_server_topology(self, server_id, main_switch, links, link_bandwidths, 
                               link_id_start, switch_id_start, npu_id_start, node_id_start,
                               link_latencies=None):
        """
        Build complete server topology including all nodes and NPUs.
        
        Args:
            server_id: Identifier for this server
            main_switch: The main switch this server connects to
            links: Dictionary to add links to
            link_bandwidths: Dictionary to add bandwidths to
            link_id_start: Starting link ID
            switch_id_start: Starting switch ID for new switches
            npu_id_start: Starting NPU ID
            node_id_start: Starting node ID
            link_latencies: Dictionary to add latencies to (optional)
            
        Returns:
            (next_link_id, next_switch_id, next_npu_id, next_node_id, tor_switch, npus_list)
        """
        link_id = link_id_start
        switch_id = switch_id_start
        npu_id = npu_id_start
        node_id = node_id_start
        
        all_npus = []
        self.server_nodes[server_id] = []
        
        # Calculate bandwidths
        intra_bw = self.intra_node_bw if self.intra_node_bw else 1.0
        inter_bw = self.inter_node_bw if self.inter_node_bw else 1.0
        intra_latency = self.intra_node_latency if self.intra_node_latency else 0.0
        inter_latency = self.inter_node_latency if self.inter_node_latency else 0.0
        
        # For switch topology with multiple NVSwitches, multiply bandwidth
        if self.intra_node_topology == 'switch':
            effective_intra_bw = intra_bw * self.num_nvswitches
        else:
            effective_intra_bw = intra_bw
        
        # Handle simple case: no intra-node topology or single NPU per node
        if self.intra_node_topology is None or (self.npus_per_node == 1 and self.nodes_per_server == 1):
            # Direct connection to main switch
            for _ in range(self.nodes_per_server):
                for _ in range(self.npus_per_node):
                    npu = f"h{npu_id}"
                    npu_id += 1
                    all_npus.append(npu)
                    
                    links[link_id] = (npu, main_switch)
                    link_bandwidths[link_id] = inter_bw
                    if link_latencies is not None:
                        link_latencies[link_id] = inter_latency
                    link_id += 1
                    links[link_id] = (main_switch, npu)
                    link_bandwidths[link_id] = inter_bw
                    if link_latencies is not None:
                        link_latencies[link_id] = inter_latency
                    link_id += 1
                    
            return link_id, switch_id, npu_id, node_id, None, all_npus
        
        # The main_switch itself serves as the ToR (no separate ToR switch)
        # Track this for backwards compatibility
        if main_switch not in self.tor_switches:
            self.tor_switches.append(main_switch)
        self.server_to_tor[server_id] = main_switch
        
        # Build each node within the server
        for n in range(self.nodes_per_server):
            # Create NPUs for this node
            npus = [f"h{npu_id + i}" for i in range(self.npus_per_node)]
            npu_id += self.npus_per_node
            all_npus.extend(npus)
            
            # Track node -> NPUs mapping
            self.node_npus[node_id] = npus
            self.server_nodes[server_id].append(node_id)
            
            # Build intra-node topology for this node
            # Connect directly to main_switch (which IS the ToR)
            if self.intra_node_topology == 'switch':
                link_id, switch_id = self._build_node_switch_topology(
                    node_id, npus, main_switch, links, link_bandwidths,
                    link_id, switch_id, effective_intra_bw, inter_bw,
                    link_latencies=link_latencies, intra_latency=intra_latency, inter_latency=inter_latency
                )
            elif self.intra_node_topology == 'ring':
                link_id, switch_id = self._build_node_ring_topology(
                    node_id, npus, main_switch, links, link_bandwidths,
                    link_id, switch_id, effective_intra_bw, inter_bw,
                    link_latencies=link_latencies, intra_latency=intra_latency, inter_latency=inter_latency
                )
            elif self.intra_node_topology == 'fully_connected':
                link_id, switch_id = self._build_node_fully_connected_topology(
                    node_id, npus, main_switch, links, link_bandwidths,
                    link_id, switch_id, effective_intra_bw, inter_bw,
                    link_latencies=link_latencies, intra_latency=intra_latency, inter_latency=inter_latency
                )
            
            node_id += 1
        
        return link_id, switch_id, npu_id, node_id, main_switch, all_npus
    
    def _build_node_switch_topology(self, node_id, npus, tor_switch, 
                                     links, link_bandwidths, link_id, switch_id, 
                                     intra_bw, inter_bw,
                                     link_latencies=None, intra_latency=0.0, inter_latency=0.0):
        """
        Build switch (NVSwitch) topology for a single node.
        NPUs connect to NVSwitch(es), NVSwitch(es) connect to main switch (ToR).
        """
        # Create NVSwitch(es) for this node
        node_nvswitches = []
        for i in range(self.num_nvswitches):
            nvswitch = f"v{switch_id}"
            switch_id += 1
            node_nvswitches.append(nvswitch)
            self.nvswitch_ids.append(nvswitch)
        
        # Connect each NPU to all NVSwitches
        for npu in npus:
            self.npu_to_intra_switches[npu] = node_nvswitches.copy()
            
            for nvswitch in node_nvswitches:
                links[link_id] = (npu, nvswitch)
                link_bandwidths[link_id] = intra_bw / self.num_nvswitches
                if link_latencies is not None:
                    link_latencies[link_id] = intra_latency
                link_id += 1
                links[link_id] = (nvswitch, npu)
                link_bandwidths[link_id] = intra_bw / self.num_nvswitches
                if link_latencies is not None:
                    link_latencies[link_id] = intra_latency
                link_id += 1
        
        # Connect NVSwitch(es) to main switch (ToR)
        for nvswitch in node_nvswitches:
            links[link_id] = (nvswitch, tor_switch)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
            links[link_id] = (tor_switch, nvswitch)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
        
        return link_id, switch_id
    
    def _build_node_ring_topology(self, node_id, npus, tor_switch,
                                   links, link_bandwidths, link_id, switch_id,
                                   intra_bw, inter_bw,
                                   link_latencies=None, intra_latency=0.0, inter_latency=0.0):
        """
        Build ring topology for a single node.
        Each NPU has a switch, switches in a ring, NIC connects to main switch (ToR).
        """
        # Create NIC switch for this node (connects to ToR)
        nic_switch = f"n{switch_id}"
        switch_id += 1
        self.nic_switches.append(nic_switch)
        
        # Create a switch for each NPU
        node_npu_switches = []
        for i, npu in enumerate(npus):
            npu_sw = f"p{switch_id}"
            switch_id += 1
            node_npu_switches.append(npu_sw)
            self.npu_switches.append(npu_sw)
            
            self.npu_to_intra_switches[npu] = [npu_sw]
            
            # Connect NPU to its switch
            links[link_id] = (npu, npu_sw)
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
            links[link_id] = (npu_sw, npu)
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
            
            # Connect NPU switch to NIC
            links[link_id] = (npu_sw, nic_switch)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
            links[link_id] = (nic_switch, npu_sw)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
        
        # Connect switches in a ring
        n = len(node_npu_switches)
        for i in range(n):
            next_i = (i + 1) % n
            links[link_id] = (node_npu_switches[i], node_npu_switches[next_i])
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
            links[link_id] = (node_npu_switches[next_i], node_npu_switches[i])
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
        
        # Connect NIC to main switch (ToR)
        links[link_id] = (nic_switch, tor_switch)
        link_bandwidths[link_id] = inter_bw
        if link_latencies is not None:
            link_latencies[link_id] = inter_latency
        link_id += 1
        links[link_id] = (tor_switch, nic_switch)
        link_bandwidths[link_id] = inter_bw
        if link_latencies is not None:
            link_latencies[link_id] = inter_latency
        link_id += 1
        
        return link_id, switch_id
    
    def _build_node_fully_connected_topology(self, node_id, npus, tor_switch,
                                              links, link_bandwidths, link_id, switch_id,
                                              intra_bw, inter_bw,
                                              link_latencies=None, intra_latency=0.0, inter_latency=0.0):
        """
        Build fully connected topology for a single node.
        Each NPU has a switch, all switches fully connected, NIC connects to main switch (ToR).
        """
        # Create NIC switch for this node (connects to ToR)
        nic_switch = f"n{switch_id}"
        switch_id += 1
        self.nic_switches.append(nic_switch)
        
        # Create a switch for each NPU
        node_npu_switches = []
        for i, npu in enumerate(npus):
            npu_sw = f"p{switch_id}"
            switch_id += 1
            node_npu_switches.append(npu_sw)
            self.npu_switches.append(npu_sw)
            
            self.npu_to_intra_switches[npu] = [npu_sw]
            
            # Connect NPU to its switch
            links[link_id] = (npu, npu_sw)
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
            links[link_id] = (npu_sw, npu)
            link_bandwidths[link_id] = intra_bw
            if link_latencies is not None:
                link_latencies[link_id] = intra_latency
            link_id += 1
            
            # Connect NPU switch to NIC
            links[link_id] = (npu_sw, nic_switch)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
            links[link_id] = (nic_switch, npu_sw)
            link_bandwidths[link_id] = inter_bw
            if link_latencies is not None:
                link_latencies[link_id] = inter_latency
            link_id += 1
        
        # Fully connect all switches
        n = len(node_npu_switches)
        for i in range(n):
            for j in range(i + 1, n):
                links[link_id] = (node_npu_switches[i], node_npu_switches[j])
                link_bandwidths[link_id] = intra_bw
                if link_latencies is not None:
                    link_latencies[link_id] = intra_latency
                link_id += 1
                links[link_id] = (node_npu_switches[j], node_npu_switches[i])
                link_bandwidths[link_id] = intra_bw
                if link_latencies is not None:
                    link_latencies[link_id] = intra_latency
                link_id += 1
        
        # Connect NIC to main switch (ToR)
        links[link_id] = (nic_switch, tor_switch)
        link_bandwidths[link_id] = inter_bw
        if link_latencies is not None:
            link_latencies[link_id] = inter_latency
        link_id += 1
        links[link_id] = (tor_switch, nic_switch)
        link_bandwidths[link_id] = inter_bw
        if link_latencies is not None:
            link_latencies[link_id] = inter_latency
        link_id += 1
        
        return link_id, switch_id

    # Keep old method for backwards compatibility
    def build_intra_node_topology(self, node_id, npus, main_switch, links, link_bandwidths, 
                                   link_id_start, switch_id_start):
        """Backwards compatible wrapper - builds single node topology."""
        link_id, switch_id, _, _, tor_switch, _ = self.build_server_topology(
            server_id=node_id,
            main_switch=main_switch,
            links=links,
            link_bandwidths=link_bandwidths,
            link_id_start=link_id_start,
            switch_id_start=switch_id_start,
            npu_id_start=int(npus[0][1:]) if npus else 1,  # Extract NPU ID from name
            node_id_start=node_id
        )
        return link_id, switch_id, tor_switch

    def generate_intra_node_paths(self, npu1, npu2):
        """
        Generate paths between two NPUs in the same node using intra-node topology.
        Returns a list of paths (each path is a list of node names).
        Stays within intra-node topology.
        """
        if self.intra_node_topology is None or self.npus_per_node == 1:
            # Direct connection
            return [[npu1, npu2]]
        
        if self.intra_node_topology == 'switch':
            # Use NVSwitch(es) - one path per NVSwitch
            paths = []
            if npu1 in self.npu_to_intra_switches:
                for nvswitch in self.npu_to_intra_switches[npu1]:
                    paths.append([npu1, nvswitch, npu2])
            return paths if paths else [[npu1, npu2]]
        
        elif self.intra_node_topology == 'ring':
            # For ring: go through the NPU switches
            # Each NPU has one switch, find shortest path on ring
            if npu1 not in self.npu_to_intra_switches or npu2 not in self.npu_to_intra_switches:
                return [[npu1, npu2]]
            
            sw1 = self.npu_to_intra_switches[npu1][0]
            sw2 = self.npu_to_intra_switches[npu2][0]
            
            # Simple path through switches
            return [[npu1, sw1, sw2, npu2]]
        
        elif self.intra_node_topology == 'fully_connected':
            # For fully connected: direct through switches
            if npu1 not in self.npu_to_intra_switches or npu2 not in self.npu_to_intra_switches:
                return [[npu1, npu2]]
            
            sw1 = self.npu_to_intra_switches[npu1][0]
            sw2 = self.npu_to_intra_switches[npu2][0]
            
            return [[npu1, sw1, sw2, npu2]]
        
        return [[npu1, npu2]]


class CustomizedDragonfly(IntraNodeTopologyMixin):
    def __init__(self, G, A, h=1, concentration=1, bandwidth_config=None, latency_config=None,
                 nodes_per_server=1, npus_per_node=1, intra_node_topology=None, num_nvswitches=1):
        self.name = "dragonfly"
        self.num_groups = G  # number of groups
        self.num_switches = A  # number of switches per group
        self.num_interpod_links_per_switch = h  # number of interpod links per switch
        self.concentration_factor = concentration  # number of servers per switch
        self.total_num_switches = G * A  # total number of switches in the topology
        self.numHostsPerPod = self.num_switches * self.concentration_factor
        
        # Server/Node/NPU configuration
        self.nodes_per_server = nodes_per_server
        self.npus_per_node = npus_per_node
        self.intra_node_topology = intra_node_topology
        self.num_nvswitches = num_nvswitches
        
        # Total counts
        self.total_num_servers = self.total_num_switches * self.concentration_factor
        self.total_num_nodes = self.total_num_servers * nodes_per_server
        self.total_num_hosts = self.total_num_nodes * npus_per_node  # Total NPUs
        
        self.adjacency_matrix = None
        self.interpod_links = []
        self.intrapod_links = []
        
        # Bandwidth Configuration
        # Expected keys: 'host_switch' (or 'inter_node'), 'intra_group', 'inter_group', 'intra_node'
        self.bandwidth_config = bandwidth_config if bandwidth_config else {}
        self.link_bandwidths = {}
        
        # Latency Configuration
        # Expected keys: 'host_switch' (or 'inter_node'), 'intra_group', 'inter_group', 'intra_node'
        self.latency_config = latency_config if latency_config else {}
        self.link_latencies = {}
        
        # Initialize intra-node configuration from mixin
        intra_node_bw = self.bandwidth_config.get('intra_node', 1.0)
        inter_node_bw = self.bandwidth_config.get('host_switch', 
                         self.bandwidth_config.get('inter_node', 1.0))
        intra_node_latency = self.latency_config.get('intra_node', 0.0)
        inter_node_latency = self.latency_config.get('host_switch',
                              self.latency_config.get('inter_node', 0.0))
        self.init_intra_node_config(
            nodes_per_server=nodes_per_server,
            npus_per_node=npus_per_node,
            intra_node_topology=intra_node_topology,
            num_nvswitches=num_nvswitches,
            intra_node_bw=intra_node_bw,
            inter_node_bw=inter_node_bw,
            intra_node_latency=intra_node_latency,
            inter_node_latency=inter_node_latency
        ) 
   
    def NumServers(self):
        return self.total_num_switches * self.concentration_factor

    def NumLinks(self):
        return 2 * int(self.num_groups*self.num_switches*(self.num_switches-1)/2 +
            self.num_groups*self.num_switches*int(float(self.num_interpod_links_per_switch))/2) # total number of directed links

    def NumSwitches(self):
        return self.total_num_switches

    def DesignIntraGroupTopology(self):
        self.adjacency_matrix = [0] * self.total_num_switches
        for switch in range(self.total_num_switches):
            self.adjacency_matrix[switch] = [0] * self.total_num_switches
        #first design the intragroup matrix in the full topology
        for i in range(self.num_groups):
            for row in range(i * self.num_switches, (i+1) * self.num_switches):
                for col in range(row+1, (i+1) * self.num_switches):
                    if row != col:
                        self.adjacency_matrix[row][col] = 1
                        self.adjacency_matrix[col][row] = 1
                        self.intrapod_links.append((row,col))

    # Non-canonical Dragonfly with potentially non-even distribution of links without any randomness
    # note: if num_intergroup_links_per_group is odd, then there will be a group with num_intergroup_links_per_group-1 interpod links
    def DesignGroupLevelTopology(self):
        num_intergroup_links_per_group = self.num_switches * self.num_interpod_links_per_switch
        eta = [[0]*self.num_groups for _ in range(self.num_groups)]
        for i in range(self.num_groups):
            for d in range(num_intergroup_links_per_group):
                mu = [num_intergroup_links_per_group+1] * self.num_groups
                for j in range(self.num_groups):
                    if i == j: continue
                    mu[j] = sum(eta[j])
                k = mu.index(min(mu))
                if i != k and sum(eta[k]) < num_intergroup_links_per_group and sum(eta[i]) < num_intergroup_links_per_group:
                    eta[i][k] += 1
                    eta[k][i] += 1
        return eta

    def DesignFullTopology(self):
        self.DesignIntraGroupTopology()
        eta = self.DesignGroupLevelTopology()
        for i in range(len(eta)):
            for j in range(i+1, len(eta[i])):
                while eta[i][j] != 0:
                    src, dst = self.find_available_src_dst(i,j)
                    eta[i][j] -= 1
                    self.adjacency_matrix[src][dst] += 1
                    self.adjacency_matrix[dst][src] += 1
                    self.interpod_links.append((src,dst))
        return

    def find_available_src_dst(self, i, j):
        src_group = i
        src_group_switches = range(src_group * self.num_switches, (src_group+1) * self.num_switches)
        src_mu = []
        for src_switch in src_group_switches:
            src_mu.append(sum(self.adjacency_matrix[src_switch]))
        src = src_mu.index(min(src_mu)) + (src_group) * self.num_switches
       
        dst_group = j
        dst_group_switches = range(dst_group * self.num_switches, (dst_group+1) * self.num_switches)
        dst_mu = []
        for dst_switch in dst_group_switches:
            dst_mu.append(sum(self.adjacency_matrix[dst_switch]))
        dst = dst_mu.index(min(dst_mu)) + (dst_group) * self.num_switches
        return src, dst

    # Exactly as described in the paper (with some randomness)
    def DesignGroupLevelTopologyV2(self):
        self.DesignIntraGroupTopology()
        #first distribute the interpod links on a pod level
        num_intergroup_links_per_group = self.num_switches * self.concentration_factor
        eta = [[0]*self.num_groups for _ in range(self.num_groups)]
        for k in range(self.num_groups):
            for d in range(num_intergroup_links_per_group):
                mu = [num_intergroup_links_per_group+1] * self.num_groups
                for i in range(self.num_groups):
                    if i == k: continue
                    mu[i] = 2*eta[i][k] + sum([eta[i][j] for j in range(self.num_groups) if j!= k])
                i_p = mu.index(min(mu))
                if sum(eta[i_p]) < num_intergroup_links_per_group and i_p != k:
                    eta[i_p][k] += 1
        return

    def writeTopologyToFile(self, path):
        with open(path, "w") as fp:
            json.dump(self.adjacency_matrix, fp)
   
    def loadTopologyFromFile(self, path):
        with open(path, "r") as fp:
            self.adjacency_matrix = json.load(fp)

    def writeLinksToFile(self, path):
        link_dict = {"interpod_links":self.interpod_links, "intrapod_links":self.intrapod_links}
        with open(path, 'w') as fp:
            json.dump(link_dict, fp)
   
    def loadLinksFromFile(self, path):
        link_dict = {}
        with open(path, "r") as fp:
            link_dict = json.load(fp)
        self.interpod_links = link_dict['interpod_links']
        self.intrapod_links = link_dict['intrapod_links']

    def WriteAdjacencyMatrixToG2ConfFile(self):
        links = []
        str_builder = "links: "
        count = 1
        for src in range(self.total_num_switches):
            for dst in range(src, self.total_num_switches):
                if self.adjacency_matrix[src][dst] != 0:
                    str_builder += ("({},t{},t{});".format(count,src+1, dst+1))
                    links.append( ("t{}".format(src+1), "t{}".format(dst+1) ) )
                    count += 1
        host_num = 1
        for switch_num in range(1, self.total_num_switches + 1):
            for _ in range(self.concentration_factor):
                str_builder += ("({},h{},t{});".format(count, host_num, switch_num))
                links.append( ("h{}".format(host_num), "t{}".format(switch_num)) )
                host_num += 1
                count += 1
        return links, str_builder, count
    
    def LinksToG2ConfFile(self):
        # Ensure self.links is populated with switch-to-switch links
        if not hasattr(self, 'links') or not self.links:
            self.writeAdjacencyMatrixToLinks()

        # Start with a copy of the existing switch-to-switch links dictionary
        links = self.links.copy()
        
        # Continue numbering from the last link ID (handle empty links dict)
        link_id = max(links.keys()) + 1 if links else 1
        switch_id = self.total_num_switches + 1  # For new switches (ToR, NVSwitch, etc.)
        
        # Track all NPUs for path generation
        self.all_npus = []
        self.node_to_npus = {}  # Maps node_id to list of NPUs
        self.npu_to_node = {}   # Maps NPU to node_id
        self.node_to_switch = {}  # Maps node_id to main switch
        
        # Server-level tracking (new 3-level hierarchy)
        self.server_to_nodes = {}  # Maps server_id to list of node_ids
        self.server_to_switch = {}  # Maps server_id to main switch
        
        server_num = 1
        node_num = 1
        npu_num = 1
        
        for switch_num in range(1, self.total_num_switches + 1):
            main_switch = f"t{switch_num}"
            
            for _ in range(self.concentration_factor):
                # Build the full server topology: Server -> Nodes -> NPUs
                result = self.build_server_topology(
                    server_id=server_num,
                    main_switch=main_switch,
                    links=links,
                    link_bandwidths=self.link_bandwidths,
                    link_id_start=link_id,
                    switch_id_start=switch_id,
                    npu_id_start=npu_num,
                    node_id_start=node_num,
                    link_latencies=self.link_latencies
                )
                link_id, switch_id, npu_num, node_num, tor_switch, server_npus = result
                
                # Record mapping from server to main switch
                self.server_to_switch[server_num] = main_switch
                
                # Update all_npus tracking
                self.all_npus.extend(server_npus)
                
                # Update node_to_npus and npu_to_node from mixin's tracking
                if server_num in self.server_nodes:
                    self.server_to_nodes[server_num] = self.server_nodes[server_num]
                    for node_id in self.server_nodes[server_num]:
                        if node_id in self.node_npus:
                            self.node_to_npus[node_id] = self.node_npus[node_id]
                            self.node_to_switch[node_id] = main_switch
                            for npu in self.node_npus[node_id]:
                                self.npu_to_node[npu] = node_id
                
                server_num += 1
        
        return links
   
    def writeAdjacencyMatrixToLinks(self):
        self.links = {}
        # self.link_bandwidths is initialized in __init__ but we populate switch links here
        # Note: This clears previous switch links but keeps the dict object
        
        intra_bw = self.bandwidth_config.get('intra_group', 1.0)
        inter_bw = self.bandwidth_config.get('inter_group', 1.0)
        intra_lat = self.latency_config.get('intra_group', 0.0)
        inter_lat = self.latency_config.get('inter_group', 0.0)
        
        # Convert interpod_links to set for faster lookup
        interpod_set = set(self.interpod_links)

        link_id = 1
        for src in range(self.total_num_switches):
            for dst in range(src, self.total_num_switches):
                if self.adjacency_matrix[src][dst] != 0:
                    self.links[link_id] = ("t{}".format(src+1), "t{}".format(dst+1))
                    
                    # Determine bandwidth and latency
                    if (src, dst) in interpod_set or (dst, src) in interpod_set:
                        self.link_bandwidths[link_id] = inter_bw
                        self.link_latencies[link_id] = inter_lat
                    else:
                        self.link_bandwidths[link_id] = intra_bw
                        self.link_latencies[link_id] = intra_lat
                        
                    link_id += 1
        
        # Add reverse links
        for i in range(link_id - 1):
            self.links[i+link_id] = (self.links[i + 1][1], self.links[i + 1][0])
            self.link_bandwidths[i+link_id] = self.link_bandwidths[i+1]
            self.link_latencies[i+link_id] = self.link_latencies[i+1]
   
    def addFlowsToFlowDict(self,flow_id,flowLinks):
        self.F[str(flow_id)] = []
        for (x,y) in flowLinks:
            if x+'-'+y in self.reverseL:
                self.F[str(flow_id)].append(self.reverseL[x+'-'+y])
            elif y+'-'+x in self.reverseL:
                self.F[str(flow_id)].append(self.reverseL[y+'-'+x])
            else:
                self.F[str(flow_id)] = []

    def addFlows(self, i, j): # for ECMP routing
        src = "t"+str(i+1)
        dst = "t"+str(j+1)
        path_lists = self.paths[src][dst]
        path_list_len = len(path_lists)
        for path_list in path_lists:
            flow_links = [(x,y) for x,y in zip(path_list, path_list[1:])]
            self.addFlowsToFlowDict(self.flow_id,flow_links)
            self.sorted_traffic[self.flow_id] = self.tm[i][j] // path_list_len
            self.flow_id += 1
   
    def GenerateUniformRouting(self):
        self.writeAdjacencyMatrixToLinks()
        G = nx.DiGraph(self.links.values())
        for link in self.interpod_links:
            G.add_edge("t{}".format(link[0]+1),"t{}".format(link[1]+1),weight=2)
            G.add_edge("t{}".format(link[1]+1),"t{}".format(link[0]+1),weight=2)
        paths = dict(nx.shortest_path(G, weight='weight'))
        return paths

    def GenerateShortestPathFlowDict(self, tm):
        print("*** Generating shortest path flow dict for dragonfly... ")
        paths = self.GenerateUniformRouting()
        self.F = {}
        self.sorted_traffic = {}
        flow_id = 1
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                src = "t"+str(i+1)
                dst = "t"+str(j+1)
                if tm[i][j] != 0:
                    forwardPathList = paths[src][dst]
                    forwardFlowLinks = [(x,y) for x,y in zip(forwardPathList, forwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,forwardFlowLinks)
                    self.sorted_traffic[flow_id] = tm[i][j]
                    flow_id += 1
                if tm[j][i] != 0:
                    backwardPathList = paths[dst][src]
                    backwardPathList = [(x,y) for x,y in zip(backwardPathList, backwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,backwardPathList)
                    self.sorted_traffic[flow_id] = tm[j][i]
                    flow_id += 1
        assert(self.F),"Error: empty return flow dict"
        return self.F, self.sorted_traffic

    def GenerateECMPFlowDict(self, tm):
        print("*** Generating ECMP flow dict for dragonfly... ")
        self.writeAdjacencyMatrixToLinks()
        G = nx.DiGraph(self.links.values())
        # for link in self.interpod_links:
        #     G.add_edge("t{}".format(link[0]+1),"t{}".format(link[1]+1))
        self.paths = {} # paths = defaultdict(lambda: defaultdict(list))
        # count = 0
        # all-to-all routing paths
        for i in range(1, int(self.total_num_switches+1)):
            src = "t{}".format(i)
            self.paths[src] = {}
            for j in range(1, int(self.total_num_switches+1)):
                if i != j:
                    dst = "t{}".format(j)
                    self.paths[src][dst] = list(nx.all_shortest_paths(G,source=src,target=dst, weight="weight"))
                    # if len(self.paths[src][dst]) > 1: count += 1
       
        self.tm = tm
        self.F = {}
        self.sorted_traffic = {}
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        self.flow_id = 1
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                if tm[i][j] != 0:
                    self.addFlows(i, j)
                if tm[j][i] != 0:
                    self.addFlows(j, i)
        return self.F, self.sorted_traffic


class Jellyfish(IntraNodeTopologyMixin):
    def __init__(self, num_switches, degree, seed=0, num_hosts_per_switch=1, bandwidth_config=None, latency_config=None,
                 nodes_per_server=1, npus_per_node=1, intra_node_topology=None, num_nvswitches=1):
        self.name = "jellyfish"
        self.num_switches = num_switches
        self.degree = degree
        self.num_hosts_per_switch = num_hosts_per_switch  # servers per switch
        self.num_intrapod_links_per_switch = self.degree
        self.seed = seed
        random.seed(self.seed)
        self.adjacency_matrix = None
        self.links = None
        self.nodes = ['t'+str(i) for i in range(1, num_switches+1)]
        
        # Server/Node/NPU configuration (3-level hierarchy)
        self.nodes_per_server = nodes_per_server
        self.npus_per_node = npus_per_node
        self.intra_node_topology = intra_node_topology
        self.num_nvswitches = num_nvswitches
        
        # Total counts in the 3-level hierarchy
        # servers = num_switches * num_hosts_per_switch (concentration)
        self.total_num_servers = self.num_switches * self.num_hosts_per_switch
        self.total_num_nodes = self.total_num_servers * nodes_per_server
        self.total_num_hosts = self.total_num_nodes * npus_per_node  # Total NPUs
        
        # For backwards compatibility
        self.concentration_factor = self.num_hosts_per_switch
        
        # Bandwidth Configuration
        # Expected keys: 'host_switch' (or 'inter_node'), 'switch_switch', 'intra_node'
        self.bandwidth_config = bandwidth_config if bandwidth_config else {}
        self.link_bandwidths = {}
        
        # Latency Configuration
        # Expected keys: 'host_switch' (or 'inter_node'), 'switch_switch', 'intra_node'
        self.latency_config = latency_config if latency_config else {}
        self.link_latencies = {}
        
        # Initialize intra-node configuration from mixin
        intra_node_bw = self.bandwidth_config.get('intra_node', 1.0)
        inter_node_bw = self.bandwidth_config.get('host_switch',
                         self.bandwidth_config.get('inter_node', 1.0))
        intra_node_latency = self.latency_config.get('intra_node', 0.0)
        inter_node_latency = self.latency_config.get('host_switch',
                              self.latency_config.get('inter_node', 0.0))
        self.init_intra_node_config(
            nodes_per_server=nodes_per_server,
            npus_per_node=npus_per_node,
            intra_node_topology=intra_node_topology,
            num_nvswitches=num_nvswitches,
            intra_node_bw=intra_node_bw,
            inter_node_bw=inter_node_bw,
            intra_node_latency=intra_node_latency,
            inter_node_latency=inter_node_latency
        )

    def NumServers(self):
        return int(self.total_num_hosts)

    def NumLinks(self):
        assert(self.adjacency_matrix), "Need to construct full topology first!"
        self.num_links = 0 # undirected links (bidirectional flow)
        for src in range(len(self.adjacency_matrix)):
            for dst in range(src+1, len(self.adjacency_matrix[src])):
                self.num_links += 2 * self.adjacency_matrix[src][dst]
        return self.num_links

    def NumSwitches(self):
        return self.num_switches

    def makeLinksFromAdjMatrix(self):
        # assume one host per switch for now
        # assume undirected links --> bidirectional flows
        assert(self.adjacency_matrix), "Need to construct full topology first!"
        self.links = {}
        self.link_weight = {}
        
        switch_bw = self.bandwidth_config.get('switch_switch', 1.0)
        switch_lat = self.latency_config.get('switch_switch', 0.0)
        
        linkID = 1
        for src in range(len(self.adjacency_matrix)):
            for dst in range(src+1, len(self.adjacency_matrix[src])):
                link_count = self.adjacency_matrix[src][dst]
                while link_count > 0:
                    self.links[linkID] = ("t" + str(src+1), "t" + str(dst+1))
                    self.link_bandwidths[linkID] = switch_bw
                    self.link_latencies[linkID] = switch_lat
                    linkID += 1
                    
                    self.links[linkID] = ("t" + str(dst+1), "t" + str(src+1))
                    self.link_bandwidths[linkID] = switch_bw
                    self.link_latencies[linkID] = switch_lat
                    linkID += 1
                    
                    link_count -= 1
        assert(linkID == self.NumLinks() + 1)

    def deletePairFromVector(self,pair, vector):
        if pair in vector:
            orig_size = len(vector)
            vector.remove(pair)
            assert(orig_size - 1 == len(vector))

    def DesignFullTopology(self):
#        print("*** Constructing Jellyfish Topology...")
        self.adjacency_matrix = [[0]*self.num_switches for _ in range(self.num_switches)]
        formed_links = [0] * self.num_switches
        # first, form a basic full mesh if there are more links per switch than there are switches
        full_mesh_n = 0
        num_intrapod_links_per_switch_copy = self.num_intrapod_links_per_switch
        while num_intrapod_links_per_switch_copy >= self.num_switches - 1:
            full_mesh_n += 1
            formed_links = [full_mesh_n * (self.num_switches - 1)] * self.num_switches
            num_intrapod_links_per_switch_copy -= self.num_switches - 1
        for i in range(self.num_switches):
            self.adjacency_matrix[i] = [full_mesh_n] * self.num_switches
            self.adjacency_matrix[i][i] = 0
        # now form the remainder of the connections
        link_pairs = []
        for src in range(self.num_switches):
            potential_targets = list(range(self.num_switches))
            random.shuffle(potential_targets)
            offset = 0
            while formed_links[src] < self.num_intrapod_links_per_switch and offset < self.num_switches:
                dst = potential_targets[offset]
                if formed_links[dst] < self.num_intrapod_links_per_switch and dst != src:
                    self.adjacency_matrix[src][dst] += 1
                    self.adjacency_matrix[dst][src] += 1
                    formed_links[src] += 1
                    formed_links[dst] += 1
                    link_pairs.append((min(src, dst), max(src , dst)))
                offset += 1
        random.shuffle(link_pairs)
        for i in range(self.num_switches):
            while self.num_intrapod_links_per_switch - formed_links[i] >= 2:
                for pair_id in range(len(link_pairs)):
                    found = False
                    if link_pairs[pair_id][0] != i and link_pairs[pair_id][1] != i:
                        sw1 = link_pairs[pair_id][0]
                        sw2 = link_pairs[pair_id][1]
                        self.adjacency_matrix[sw1][sw2] -= 1
                        self.adjacency_matrix[sw2][sw1] -= 1
                        self.adjacency_matrix[i][sw1] += 1
                        self.adjacency_matrix[sw1][i] += 1
                        self.adjacency_matrix[i][sw2] += 1
                        self.adjacency_matrix[sw2][i] += 1
                        formed_links[i] += 2
                        link_pairs.pop(pair_id)
                        found = True
                    if found:
                        break
        self.makeLinksFromAdjMatrix()

    def WriteAdjacencyMatrixToG2ConfFile(self):
        
        str_builder = "links: "
        count = 1
        #for link_id, (src, dst) in self.links.items():
        #    str_builder += ("({},s{},s{});".format(count,src+1, dst+1))

        return self.links, str_builder, count

    def LinksToG2ConfFile(self):
        # Ensure self.links is populated with switch-to-switch links
        if not self.links:
            self.makeLinksFromAdjMatrix()

        # Start with a copy of the existing switch-to-switch links dictionary
        links = self.links.copy()

        # Continue numbering from the last link ID (handle empty links dict)
        link_id = max(links.keys()) + 1 if links else 1
        switch_id = self.num_switches + 1  # For new switches (ToR, NVSwitch, etc.)
        
        # Track all NPUs for path generation
        self.all_npus = []
        self.node_to_npus = {}  # Maps node_id to list of NPUs
        self.npu_to_node = {}   # Maps NPU to node_id
        self.node_to_switch = {}  # Maps node_id to main switch
        
        # Server-level tracking (3-level hierarchy)
        self.server_to_nodes = {}
        self.server_to_switch = {}
        
        server_num = 1
        node_num = 1
        npu_num = 1
        
        for switch_num in range(1, self.num_switches + 1):
            main_switch = f"t{switch_num}"
            
            for _ in range(self.num_hosts_per_switch):
                # Build the full server topology: Server -> Nodes -> NPUs
                result = self.build_server_topology(
                    server_id=server_num,
                    main_switch=main_switch,
                    links=links,
                    link_bandwidths=self.link_bandwidths,
                    link_id_start=link_id,
                    switch_id_start=switch_id,
                    npu_id_start=npu_num,
                    node_id_start=node_num,
                    link_latencies=self.link_latencies
                )
                link_id, switch_id, npu_num, node_num, tor_switch, server_npus = result
                
                # Record mapping from server to main switch
                self.server_to_switch[server_num] = main_switch
                
                # Update all_npus tracking
                self.all_npus.extend(server_npus)
                
                # Update node_to_npus and npu_to_node from mixin's tracking
                if server_num in self.server_nodes:
                    self.server_to_nodes[server_num] = self.server_nodes[server_num]
                    for node_id in self.server_nodes[server_num]:
                        if node_id in self.node_npus:
                            self.node_to_npus[node_id] = self.node_npus[node_id]
                            self.node_to_switch[node_id] = main_switch
                            for npu in self.node_npus[node_id]:
                                self.npu_to_node[npu] = node_id
                
                server_num += 1
        
        return links
    
    def addFlowsToFlowDict(self,flow_id,flowLinks):
        self.F[flow_id] = []
        for (x,y) in flowLinks:
            if x+'-'+y in self.reverseL:
                self.F[flow_id].append(self.reverseL[x+'-'+y])
            elif y+'-'+x in self.reverseL:
                self.F[flow_id].append(self.reverseL[y+'-'+x])
            else:
                self.F[flow_id] = []

    def addFlows(self, i, j): # for ECMP routing
        src = "t"+str(i+1)
        dst = "t"+str(j+1)
        path_lists = self.paths[src][dst]
        path_list_len = len(path_lists)
        for path_list in path_lists:
            flow_links = [(x,y) for x,y in zip(path_list, path_list[1:])]
            self.addFlowsToFlowDict(self.flow_id,flow_links)
            self.sorted_traffic[self.flow_id] = self.tm[i][j] // path_list_len
            self.flow_id += 1

    def GenerateUniformRouting(self):
        self.makeLinksFromAdjMatrix()
        G = nx.MultiDiGraph()
        G.add_edges_from(self.links.values())
        self.paths = dict(nx.shortest_path(G))
        return self.paths

    def GenerateShortestPathFlowDict(self, tm):
        print("*** Generating flow dict for Jellyfish...")
        self.GenerateUniformRouting()
        self.F = {}
        self.sorted_traffic = {}
        flow_id = 1
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                src = "t" + str(i+1)
                dst = "t" + str(j+1)
                if tm[i][j] != 0:
                    forwardPathList = self.paths[src][dst]
                    forwardFlowLinks = [(x,y) for x,y in zip(forwardPathList, forwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,forwardFlowLinks)
                    self.sorted_traffic[flow_id] = tm[i][j]
                    flow_id += 1
                if tm[j][i] != 0:
                    backwardPathList = self.paths[dst][src]
                    backwardFlowLinks = [(x,y) for x,y in zip(backwardPathList, backwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,backwardFlowLinks)
                    self.sorted_traffic[flow_id] = tm[j][i]
                    flow_id += 1
        assert(self.F),"Error: empty return flow dict"
        return self.F, self.sorted_traffic

   
    def GenerateECMPFlowDict(self, tm):
        print("*** Generating flow dict for Jellyfish...")
        self.makeLinksFromAdjMatrix()
        G = nx.MultiDiGraph()
        G.add_edges_from(self.links.values())
        # paths = (nx.shortest_path(G))
        self.paths = {}
        for i in range(1, int(self.num_switches+1)):
            src = "t{}".format(i)
            self.paths[src] = {}
            for j in range(1, int(self.num_switches+1)):
                if i != j:
                    dst = "t{}".format(j)
                    self.paths[src][dst] = list(nx.all_shortest_paths(G,source=src,target=dst))
        self.tm = tm
        self.F = {}
        self.sorted_traffic = {}
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        self.flow_id = 1
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                if tm[i][j] != 0:
                    self.addFlows(i, j)
                if tm[j][i] != 0:
                    self.addFlows(j, i)
        return self.F, self.sorted_traffic


class FoldedClos(IntraNodeTopologyMixin):
    def __init__(self, K, link_capacity=1, N=3, bandwidth_config=None, latency_config=None,
                 nodes_per_server=1, npus_per_node=1, intra_node_topology=None, num_nvswitches=1):
        self.name = "folded_clos"
        self.K = K
        self.numCoreSwitches = K**2 / 4
        self.numSwitchesPerPod = K
        self.numSwitchPorts = K
        self.totalNumSwitches = int(self.numSwitchesPerPod * self.K + self.numCoreSwitches)
        self.links = {}
        self.c_dict = None
        self.link_capacity = link_capacity
        self.adjacency_matrix = [[0] * self.totalNumSwitches for _ in range(self.totalNumSwitches)]
        self.num_switches = sum([K**n for n in range(N)])
        self.switches = [self._switch_name(i) for i in range(1, self.totalNumSwitches+1)]
        
        # Server/Node/NPU configuration (3-level hierarchy)
        self.nodes_per_server = nodes_per_server
        self.npus_per_node = npus_per_node
        self.intra_node_topology = intra_node_topology
        self.num_nvswitches = num_nvswitches
        
        # In FoldedClos, numServers refers to the number of "servers"
        # Each server can have multiple nodes, each node has multiple NPUs
        self.numServers = K**3 / 4  # This is the number of servers
        self.numServersPerPod = K**2 / 4
        self.numHostsPerPod = self.numServersPerPod  # For backwards compatibility
        
        # Total counts in the 3-level hierarchy
        self.total_num_servers = int(self.numServers)
        self.total_num_nodes = int(self.numServers * nodes_per_server)
        self.numNodes = self.total_num_nodes  # Backwards compatibility
        self.numHosts = self.total_num_nodes * npus_per_node  # Total NPUs
        self.total_num_hosts = self.numHosts
        
        # For backwards compatibility 
        self.concentration_factor = 1  # FoldedClos has fixed concentration
        
        self.hosts = ['h'+str(i) for i in range(1, int(self.numHosts)+1)]
        self.nodes = self.hosts + self.switches
        
        # Track FoldedClos switch layers
        self.edge_switches = []   # Edge switches (these ARE the ToRs)
        self.agg_switches = []    # Aggregation switches
        self.core_switches = []   # Core switches
        
        # Bandwidth Configuration
        # Expected keys: 'host_edge' (or 'inter_node'), 'edge_agg', 'agg_core', 'intra_node'
        self.bandwidth_config = bandwidth_config if bandwidth_config else {}
        self.link_bandwidths = {}
        
        # Latency Configuration
        # Expected keys: 'host_edge' (or 'inter_node'), 'edge_agg', 'agg_core', 'intra_node'
        self.latency_config = latency_config if latency_config else {}
        self.link_latencies = {}
        
        # Initialize intra-node configuration from mixin
        intra_node_bw = self.bandwidth_config.get('intra_node', 1.0)
        inter_node_bw = self.bandwidth_config.get('host_edge',
                         self.bandwidth_config.get('inter_node', 1.0))
        intra_node_latency = self.latency_config.get('intra_node', 0.0)
        inter_node_latency = self.latency_config.get('host_edge',
                              self.latency_config.get('inter_node', 0.0))
        self.init_intra_node_config(
            nodes_per_server=nodes_per_server,
            npus_per_node=npus_per_node,
            intra_node_topology=intra_node_topology,
            num_nvswitches=num_nvswitches,
            intra_node_bw=intra_node_bw,
            inter_node_bw=inter_node_bw,
            intra_node_latency=intra_node_latency,
            inter_node_latency=inter_node_latency
        )

    def _switch_name(self, idx):
        """Map switch index to prefixed name based on layer type.
        
        Edge/ToR switches → 't', Aggregation switches → 'a', Core switches → 'c'.
        """
        core_start = int(self.numSwitchesPerPod * self.K + 1)
        if idx >= core_start:
            return f'c{idx}'
        pos_in_pod = (idx - 1) % int(self.numSwitchesPerPod)
        if pos_in_pod < self.numSwitchesPerPod // 2:
            return f't{idx}'  # edge/ToR
        else:
            return f'a{idx}'  # aggregation

    def NumServers(self):
        return int(self.numHosts)

    def NumLinks(self):
        return int(len(self.links))

    def NumSwitches(self):
        return self.totalNumSwitches

    def DesignFullTopology(self):
        """
        Design the full FoldedClos topology with optional intra-node topology support.
        
        Server/Node/NPU hierarchy:
        - Each "server" (concentration) connects to an edge switch
        - If nodes_per_server > 1, server has a ToR connecting to edge switch
        - Each node within server has NPUs connected via intra-node topology
        """
        linkID = 1
        
        bw_host_edge = self.bandwidth_config.get('host_edge', 
                        self.bandwidth_config.get('inter_node', 1.0))
        bw_edge_agg = self.bandwidth_config.get('edge_agg', 1.0)
        bw_agg_core = self.bandwidth_config.get('agg_core', 1.0)
        
        lat_host_edge = self.latency_config.get('host_edge',
                         self.latency_config.get('inter_node', 0.0))
        lat_edge_agg = self.latency_config.get('edge_agg', 0.0)
        lat_agg_core = self.latency_config.get('agg_core', 0.0)
        
        # Track NPU and node information
        self.all_npus = []
        self.node_to_npus = {}
        self.npu_to_node = {}
        self.node_to_switch = {}  # Maps node to its edge switch
        
        # Server-level tracking (3-level hierarchy)
        self.server_to_nodes = {}
        self.server_to_switch = {}
        
        npu_num = 1
        node_num = 1
        server_num = 1
        switch_id = self.totalNumSwitches + 1  # For new switches (NVSwitch, etc.)
        
        # Populate core switches list
        core_start = int(self.numSwitchesPerPod * self.K + 1)
        core_end = int(core_start + self.numCoreSwitches)
        self.core_switches = [f'c{i}' for i in range(core_start, core_end)]
        
        for pod in range(self.K):
            coreSwitchStart = int(self.numSwitchesPerPod * self.K + 1)
            EdgeSwitchStart = int(pod * self.numSwitchesPerPod + 1)
            EdgeSwitchEnd = int((pod + 1/2) * self.numSwitchesPerPod)
            aggSwitchStart = int(EdgeSwitchEnd + 1)
            aggSwitchEnd = int(EdgeSwitchEnd + self.numSwitchesPerPod // 2)
            
            # Track edge and aggregation switches
            for eS in range(EdgeSwitchStart, EdgeSwitchEnd + 1):
                sw_name = f't{eS}'
                if sw_name not in self.edge_switches:
                    self.edge_switches.append(sw_name)
            for aS in range(aggSwitchStart, aggSwitchEnd + 1):
                sw_name = f'a{aS}'
                if sw_name not in self.agg_switches:
                    self.agg_switches.append(sw_name)

            # Connect servers (with nodes/NPUs) to edge switches
            for eS in range(EdgeSwitchStart, EdgeSwitchEnd + 1):
                edge_switch = f"t{eS}"
                servers_per_edge = int(self.numSwitchPorts // 2)
                
                for s in range(servers_per_edge):
                    # Build the full server topology: Server -> Nodes -> NPUs
                    result = self.build_server_topology(
                        server_id=server_num,
                        main_switch=edge_switch,
                        links=self.links,
                        link_bandwidths=self.link_bandwidths,
                        link_id_start=linkID,
                        switch_id_start=switch_id,
                        npu_id_start=npu_num,
                        node_id_start=node_num,
                        link_latencies=self.link_latencies
                    )
                    linkID, switch_id, npu_num, node_num, tor_switch, server_npus = result
                    
                    # Record mapping from server to edge switch
                    self.server_to_switch[server_num] = edge_switch
                    
                    # Update all_npus tracking
                    self.all_npus.extend(server_npus)
                    
                    # Update node_to_npus and npu_to_node from mixin's tracking
                    if server_num in self.server_nodes:
                        self.server_to_nodes[server_num] = self.server_nodes[server_num]
                        for node_id in self.server_nodes[server_num]:
                            if node_id in self.node_npus:
                                self.node_to_npus[node_id] = self.node_npus[node_id]
                                self.node_to_switch[node_id] = edge_switch
                                for npu in self.node_npus[node_id]:
                                    self.npu_to_node[npu] = node_id
                    
                    server_num += 1
                    
            # Connect edge switches to aggregation switches
            for aS in range(aggSwitchStart, aggSwitchEnd + 1):
                for eS in range(EdgeSwitchStart, EdgeSwitchEnd + 1):
                    self.links[linkID] = (f'a{aS}', f't{eS}')
                    self.link_bandwidths[linkID] = bw_edge_agg
                    self.link_latencies[linkID] = lat_edge_agg
                    linkID += 1
                    
                # Connect aggregation switches to core switches
                for cS in range(self.numSwitchPorts // 2):
                    self.links[linkID] = (f'c{coreSwitchStart + cS}', f'a{aS}')
                    self.link_bandwidths[linkID] = bw_agg_core
                    self.link_latencies[linkID] = lat_agg_core
                    linkID += 1
                coreSwitchStart += self.numSwitchPorts // 2
        
        # Create reverse links (bidirectional)
        num_forward_links = linkID - 1
        for i in range(num_forward_links):
            src, dst = self.links[i + 1]
            self.links[i + linkID] = (dst, src)
            self.link_bandwidths[i + linkID] = self.link_bandwidths[i + 1]
            self.link_latencies[i + linkID] = self.link_latencies[i + 1]
            
        self.num_links = linkID

    def LinksToG2ConfFile(self):
        str_builder = "links: "
        for id, link in self.links.items():
            str_builder += ("(s{},s{});".format(link[0], link[1]))
        return self.links, str_builder

    def GenerateUniformRouting(self, tapering_num = 0):
        """Generate the shortest path routing with balanced link loads for the clos-pods structure.
        The routing algorithm is compatiable with the algorithm described in http://ccr.sigcomm.org/online/files/p63-alfares.pdf
        Args:
            links (dict): Dictionary of the link information (key, value) = (linkID, (src, dst)).
            K (int): The number of pods in the clos-pods structure.
        Returns:
            list: The routing list Paths[src][dst] = [all transversed nodes].
        Examples:
            paths = GenerateUniformRouting(links, 4)
        """

        assert (float(self.numCoreSwitches).is_integer() and float(self.numHosts).is_integer()),"K is not appropriate!"
        # start_time = time.time()
        G = nx.Graph()
        G.add_edges_from(self.links.values())
        # print("Time to build networks:", str(time.time() - start_time))
        paths = dict(nx.shortest_path(G))
        # print("Time to find all shortest paths:", str(time.time() - start_time))
        # Intra-Pod inter-EdgeSwitch routing
        # If source is the ith host in mth edge switch and destination is the jth host in nth edge switch,
        # the routing will transverse ath aggregation switch, a = (j + m) mod (k/2).
        # The remaining transversed nodes are then deterministic.
        for podID in range(self.K):
            for esrc, edst in permutations(range(1, self.numSwitchesPerPod // 2 + 1),2):
                for hsrc, hdst in product(range(1, self.numSwitchPorts // 2+1),range(1, self.numSwitchPorts // 2 + 1)):
                    eOutPort = (hdst - 1 + esrc - 1) % (self.numSwitchesPerPod // 2) + 1
                    hSrcID = podID * self.numHostsPerPod + (esrc - 1)*self.numSwitchPorts // 2 + hsrc
                    hDstID = podID * self.numHostsPerPod + (edst - 1)*self.numSwitchPorts // 2 + hdst
                    eSrcID = podID * self.numSwitchesPerPod + esrc
                    eDstID = podID * self.numSwitchesPerPod + edst
                    aID    = podID * self.numSwitchesPerPod + self.numSwitchesPerPod // 2 + eOutPort
                    paths["h" + str(int(hSrcID))]["h" + str(int(hDstID))] = ['h' + str(int(hSrcID)),'t' + str(int(eSrcID)),'a' + str(int(aID)),'t' + str(int(eDstID)),'h' + str(int(hDstID))]
        # Inter-Pod routing
        # If source is the ith host in mth edge switch within pod k1, and destination is the jth host in nth edge switch within pod k2,
        # the routing will transverse ath aggregation switch in pod k1, a = (j + m) mod (k/2),
        # and transverse the kth core switch, k = (a + m) mod (k/2).
        # The remaining transversed nodes are then deterministic.

        for psrc, pdst in permutations(range(self.K),2):
            for esrc, edst in product(range(1, self.numSwitchesPerPod // 2 + 1), range(1, self.numSwitchesPerPod // 2 + 1)):
                for hsrc, hdst in product(range(1, self.numSwitchPorts // 2 + 1),range(1, self.numSwitchPorts // 2 + 1)):
                    eOutPort = (hdst - 1 + esrc -1) % (self.numSwitchesPerPod // 2) + 1
                    hSrcID = int(psrc * self.numHostsPerPod + (esrc - 1) * self.numSwitchPorts // 2 + hsrc)
                    hDstID = int(pdst * self.numHostsPerPod + (edst - 1)*self.numSwitchPorts // 2 + hdst)
                    eSrcID = int(psrc * self.numSwitchesPerPod + esrc)
                    eDstID = int(pdst * self.numSwitchesPerPod + edst)
                    aSrcID = int(psrc * self.numSwitchesPerPod + self.numSwitchesPerPod // 2 + eOutPort)
                    aDstID = int(pdst * self.numSwitchesPerPod + self.numSwitchesPerPod // 2 + eOutPort)
                    aOutPort = int((hdst - 1 + eOutPort - 1) % (self.numSwitchesPerPod // 2 - tapering_num) + 1)
                    coreID = int(self.numSwitchesPerPod * self.K + (eOutPort - 1) * self.numSwitchPorts // 2 + aOutPort)

                    paths["h" + str(hSrcID)]["h" + str(hDstID)] = ['h' + str(hSrcID),'t' + str(eSrcID),'a' + str(aSrcID),'c' + str(coreID),'a' + str(aDstID),'t' + str(eDstID),'h' + str(hDstID)]        
        # print("Time to generate all clos paths:", str(time.time() - start_time))
        return paths

    def addFlowsToFlowDict(self,flow_id,flowLinks):
        self.F[flow_id] = []
        for (x,y) in flowLinks:
            if x+'-'+y in self.reverseL:
                self.F[flow_id].append(self.reverseL[x+'-'+y])
            elif y+'-'+x in self.reverseL:
                self.F[flow_id].append(self.reverseL[y+'-'+x])
            else:
                self.F[flow_id] = []

    def addFlows(self, i, j): # for ECMP routing
        src = "h"+str(i+1)
        dst = "h"+str(j+1)
        path_lists = self.paths[src][dst]
        path_list_len = len(path_lists)
        for path_list in path_lists:
            flow_links = [(x,y) for x,y in zip(path_list, path_list[1:])]
            self.addFlowsToFlowDict(self.flow_id,flow_links)
            self.sorted_traffic[self.flow_id] = self.tm[i][j] // path_list_len
            self.flow_id += 1

    def GenerateShortestPathFlowDict(self, tm):
        print("*** Generating flow dict for folded clos K = {}".format(self.K))
        self.paths = self.GenerateUniformRouting()
        # start_time = time.time()
        self.F = {}
        self.sorted_traffic = {}
        flow_id = 1
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                src = "h"+str(i+1)
                dst = "h"+str(j+1)
                if tm[i][j] != 0:
                    forwardPathList = self.paths[src][dst]
                    forwardFlowLinks = [(x,y) for x,y in zip(forwardPathList, forwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,forwardFlowLinks)
                    self.sorted_traffic[flow_id] = tm[i][j]
                    flow_id += 1
                if tm[j][i] != 0:
                    backwardPathList = self.paths[dst][src]
                    backwardFlowLinks = [(x,y) for x,y in zip(backwardPathList, backwardPathList[1:])]
                    self.addFlowsToFlowDict(flow_id,backwardFlowLinks)
                    self.sorted_traffic[flow_id] = tm[j][i]
                    flow_id += 1
        assert(self.F),"Error: empty return flow dict"
        # print("Time to generate f dict:", str(time.time() - start_time))
        return self.F, self.sorted_traffic

    def compute_fabric_ecmp_paths(self, max_paths=1):
        """
        Compute ECMP paths between all edge-switch pairs using only the fabric
        subgraph (edge + agg + core switches, no NPUs or NVSwitches).

        This is orders-of-magnitude faster than GenerateECMPFlowDict for large
        topologies because:
          - Fabric subgraph: O(K²) nodes  vs  full graph O(K³) nodes
          - Only N_edge_switch² pairs     vs  N_NPU² pairs
        For K=16: 320-node graph, 128²=16K pairs  vs  12K-node graph, 8192²=67M pairs.

        Args:
            max_paths: Maximum paths per edge-switch pair.
                       1  → one deterministic shortest path (default, fast & compact).
                       None → all shortest paths (can be very large for big K).

        Returns:
            dict: fabric_paths[src_edge][dst_edge] = list_of_paths
                  Each path is a list of switch names [src_edge, ..., dst_edge].
        """
        fabric_nodes = set(self.edge_switches + self.agg_switches + self.core_switches)

        G_fabric = nx.DiGraph()
        for (src, dst) in self.links.values():
            if src in fabric_nodes and dst in fabric_nodes:
                G_fabric.add_edge(src, dst)

        n_edge = len(self.edge_switches)
        print(f"  Fabric subgraph: {G_fabric.number_of_nodes()} nodes, "
              f"{G_fabric.number_of_edges()} edges")
        print(f"  Computing paths between {n_edge} edge switches "
              f"({n_edge * (n_edge - 1):,} directed pairs)...")

        fabric_paths = {}
        for src in self.edge_switches:
            fabric_paths[src] = {}
            for dst in self.edge_switches:
                if src == dst:
                    continue
                try:
                    if max_paths == 1:
                        fabric_paths[src][dst] = [nx.shortest_path(G_fabric, src, dst)]
                    else:
                        paths = list(nx.all_shortest_paths(G_fabric, src, dst))
                        fabric_paths[src][dst] = paths if max_paths is None else paths[:max_paths]
                except (nx.NetworkXNoPath, nx.NodeNotFound):
                    fabric_paths[src][dst] = []

        return fabric_paths

    def GenerateECMPFlowDict(self, tm):
        print("*** Generating ECMP flow dict for folded clos K = {}".format(self.K))
        G = nx.DiGraph(self.links.values())
        self.paths = {}
        for i in range(1, int(self.numHosts+1)):
            src = "h{}".format(i)
            self.paths[src] = {}
            for j in range(1, int(self.numHosts+1)):
                if i != j:
                    dst = "h{}".format(j)
                    self.paths[src][dst] = list(nx.all_shortest_paths(G,source=src,target=dst, weight="weight"))
        self.tm = tm
        self.F = {}
        self.sorted_traffic = {}
        self.reverseL = dict( (v[0]+"-"+v[1],k)for k,v in self.links.items() )
        self.flow_id = 1
        for i in range(len(tm)):
            for j in range(i+1, len(tm[i])):
                if tm[i][j] != 0:
                    self.addFlows(i, j)
                if tm[j][i] != 0:
                    self.addFlows(j, i)
        return self.F, self.sorted_traffic