#!/usr/bin/env bash
set -euo pipefail

# Cleanup script for core dumps generated by crashed processes in the SLURM suite.
# Targets files named: core.<number>

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR"
DRY_RUN=0
ASSUME_YES=0

print_usage() {
  cat <<'EOF'
Usage: cleanup_core_files.sh [options]

Options:
  --root <dir>   Root directory to scan (default: script directory)
  --dry-run      Show what would be deleted without deleting
  --yes          Do not prompt for confirmation
  -h, --help     Show this help

Examples:
  ./cleanup_core_files.sh --dry-run
  ./cleanup_core_files.sh --yes
  ./cleanup_core_files.sh --root ./experiments --yes
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      if [[ $# -lt 2 ]]; then
        echo "Error: --root requires a directory argument." >&2
        exit 1
      fi
      ROOT_DIR="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --yes)
      ASSUME_YES=1
      shift
      ;;
    -h|--help)
      print_usage
      exit 0
      ;;
    *)
      echo "Error: Unknown option '$1'" >&2
      print_usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -d "$ROOT_DIR" ]]; then
  echo "Error: root directory does not exist: $ROOT_DIR" >&2
  exit 1
fi

# Canonical path for clearer output
ROOT_DIR="$(cd "$ROOT_DIR" && pwd)"

mapfile -d '' CORE_FILES < <(find "$ROOT_DIR" -type f -name 'core.[0-9]*' -print0)
COUNT="${#CORE_FILES[@]}"

if [[ "$COUNT" -eq 0 ]]; then
  echo "No core dump files found under: $ROOT_DIR"
  exit 0
fi

echo "Found $COUNT core dump file(s) under: $ROOT_DIR"
for f in "${CORE_FILES[@]}"; do
  echo "  $f"
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo
  echo "Dry run only. No files were deleted."
  exit 0
fi

if [[ "$ASSUME_YES" -ne 1 ]]; then
  echo
  read -r -p "Delete these $COUNT file(s)? [y/N] " reply
  case "$reply" in
    y|Y|yes|YES)
      ;;
    *)
      echo "Aborted."
      exit 0
      ;;
  esac
fi

DELETED=0
for f in "${CORE_FILES[@]}"; do
  rm -f -- "$f"
  DELETED=$((DELETED + 1))
done

echo "Deleted $DELETED core dump file(s)."
